# fly.toml app configuration file generated for fronton-torneos-web on 2026-05-20T19:11:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fronton-torneos-web'
primary_region = 'gru'

[build]
  [build.args]
    VITE_API_BASE_URL = "https://fronton-torneos-api.fly.dev"
    VITE_SUPABASE_URL = "https://rmssrsitwmgxyqizvkjz.supabase.co"
    VITE_SUPABASE_ANON_KEY = "sb_publishable_HPqSIGaqGsLmX1dclfA6rg_dATwv6SH"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
